project = "shanhaijing"

[server]
addr = "192.168.31.76"    #ip地址
port = "5555"   #开放的端口号
name = "game1"   #节点名称
group_id = "0"  #组名
node_type = 2   #网关：1， node：2，client：3
listen_mode = "tcp"  #监听模式，tcp监听还是websocket监听，默认为tcp，
web_port = "8080"   #web监听端口

[etcd]
addr = ["127.0.0.1:2379","192.168.1.2:2380"] #etcd地址，ip+端口号，如果是集群，则是列表形式
username = "root" #etcd用户名
password = "123456" #etcd密码


[logging]
level = "debug" #日志等级
log_path = ""  #日志名称,默认情况下是运行目录下的logs
max_size = 2104298746 #日志最大容量，单位byte
max_backups = 10 #最多多少个备份，
max_age = 24 #最大多少时间轮转一次日志,单位小时